name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: build
      run: go build -v ./...

    - name: test
      run: go test -v -race -cpu 1,2,4 ./...

    - name: staticcheck
      run: |
        go get honnef.co/go/tools/cmd/staticcheck
        staticcheck ./...

    - name: gofmt
      run: |
        gofmt -l -s -d .

    - name: goimports
      run: |
        go get golang.org/x/tools/cmd/goimports
        goimports -l -d .

    - name: errcheck
      run: |
        go get github.com/kisielk/errcheck
        errcheck -blank -asserts ./...
  
  test:
    name: test
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -cover -timeout 2m
